version: '3.9'

services:
  app:
    build: .
    container_name: dealls-app
    ports:
      - "8010:8010"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: dealls-dwi
      DB_PASSWORD: 12345
      DB_NAME: dealls
    restart: always

  db:
    image: postgres:15
    container_name: dealls-db
    environment:
      POSTGRES_USER: dealls-dwi
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: dealls
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
